In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_pickle(r"C:\Users\Almog\Desktop\Data Science\Projects\2026\Customer Personality Analysis\Pickle files\FE_MC1.pkl")
df.head()

,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,tenure_years,Education_ord,Marital_Status_encoded,total_spending,total_purchases,is_web_dominant,value_optimizer,spending_to_income_ratio,family_load,is_long_tenure
0,1957,58138.0,0,0,58,635,88,546,172,88,...,1.815,2,2,1617,12,1,0,0.027813,0,1
1,1954,46344.0,1,1,38,11,1,6,2,1,...,0.309,2,2,27,3,0,0,0.000583,1,0
2,1965,71613.0,0,0,26,426,49,127,111,21,...,0.854,2,1,776,18,0,0,0.010836,0,0
3,1984,26646.0,1,0,26,11,4,20,10,3,...,0.381,2,1,53,6,0,0,0.001989,1,0
4,1981,58293.0,1,0,94,173,43,118,46,27,...,0.441,4,0,422,11,0,0,0.007239,1,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year_Birth                2240 non-null   int64
 1   Income                    2240 non-null   float64
 2   Kidhome                   2240 non-null   int64
 3   Teenhome                  2240 non-null   int64
 4   Recency                   2240 non-null   int64
 5   MntWines                  2240 non-null   int64
 6   MntFruits                 2240 non-null   int64
 7   MntMeatProducts           2240 non-null   int64
 8   MntFishProducts           2240 non-null   int64
 9   MntSweetProducts          2240 non-null   int64
 10  MntGoldProds              2240 non-null   int64
 11  NumDealsPurchases         2240 non-null   int64
 12  NumWebPurchases           2240 non-null   int64
 13  NumCatalogPurchases       2240 non-null   int64
 14  NumStorePurchases         2240 non-null   int64
 15  NumWebVisitsMonth         2240 non-null   int64
 16  AcceptedCmp3              2240 non-null   int64
 17  AcceptedCmp4              2240 non-null   int64
 18  AcceptedCmp5              2240 non-null   int64
 19  AcceptedCmp1              2240 non-null   int64
 20  AcceptedCmp2              2240 non-null   int64
 21  Complain                  2240 non-null   int64
 22  Response                  2240 non-null   int64
 23  tenure_years              2240 non-null   float64
 24  Education_ord             2240 non-null   int64
 25  Marital_Status_encoded    2240 non-null   int64
 26  total_spending            2240 non-null   int64
 27  total_purchases           2240 non-null   int64
 28  is_web_dominant           2240 non-null   int32
 29  value_optimizer           2240 non-null   int32
 30  spending_to_income_ratio  2240 non-null   float64
 31  family_load               2240 non-null   int32
 32  is_long_tenure            2240 non-null   int32
dtypes: float64(3), int32(4), int64(26)
memory usage: 542.6 KB

#### Featrue Selection

Because clustering has no target variable, we cannot use classifiers to evaluate predictive importance. Instead, we measure how much each feature contributes to cluster structure. The code above first calculates a baseline silhouette score using all features. Then it removes each feature one at a time, reruns clustering, and measures the new silhouette score. If removing a feature reduces the silhouette score, the feature is important for forming clusters; if removing it improves or barely changes the score, the feature may be redundant or noisy and can potentially be dropped. This gives you a practical unsupervised feature selection ranking similar in spirit to your supervised voting approach.

**Silhouette_without_feature**
The silhouette score obtained after removing that feature and rerunning clustering. It measures how well the clusters are separated when that feature is excluded.

**Impact**
The difference between the baseline silhouette score (with all features) and the silhouette score after removing the feature.

- Positive Impact → removing the feature worsens clustering → the feature is important.

- Negative Impact → removing the feature improves clustering → the feature may be noise or redundant.

In [6]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Assume df is already numeric and ready
X = df.copy()

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Baseline clustering
kmeans = KMeans(n_clusters=4, random_state=42)
labels = kmeans.fit_predict(X_scaled)
baseline_score = silhouette_score(X_scaled, labels)

results = []

# Leave-one-feature-out evaluation
for col in X.columns:
    X_reduced = X.drop(columns=[col])
    
    scaler = StandardScaler()
    X_scaled_reduced = scaler.fit_transform(X_reduced)

    kmeans = KMeans(n_clusters=4, random_state=42)
    labels = kmeans.fit_predict(X_scaled_reduced)

    score = silhouette_score(X_scaled_reduced, labels)

    results.append({
        "Feature": col,
        "Silhouette_without_feature": score,
        "Impact": baseline_score - score
    })

selection_df = pd.DataFrame(results).sort_values("Impact", ascending=False)

In [7]:


# Copy results
feature_summary = selection_df.copy()

# Function to categorize importance
def categorize_feature(impact):
    if impact >= 0.08:
        return "Strongly Influential"
    elif impact >= 0.01:
        return "Moderately Contributing"
    elif impact >= 0:
        return "Low Influence"
    else:
        return "Potential Noise"

# Apply categorization
feature_summary["Category"] = feature_summary["Impact"].apply(categorize_feature)

# Add rank column
feature_summary["Rank"] = feature_summary["Impact"].rank(ascending=False).astype(int)

# Sort by rank
feature_summary = feature_summary.sort_values("Rank")

feature_summary

,Feature,Silhouette_without_feature,Impact,Category,Rank
23,tenure_years,0.081856,0.104735,Strongly Influential,1
1,Income,0.092270,0.094320,Strongly Influential,2
11,NumDealsPurchases,0.093556,0.093034,Strongly Influential,3
30,spending_to_income_ratio,0.094172,0.092418,Strongly Influential,4
21,Complain,0.094765,0.091825,Strongly Influential,5
10,MntGoldProds,0.096179,0.090412,Strongly Influential,6
16,AcceptedCmp3,0.098035,0.088555,Strongly Influential,7
20,AcceptedCmp2,0.098198,0.088392,Strongly Influential,8
0,Year_Birth,0.098789,0.087801,Strongly Influential,9
4,Recency,0.100711,0.085879,Strongly Influential,10
12,NumWebPurchases,0.104083,0.082508,Strongly Influential,11
25,Marital_Status_encoded,0.108282,0.078308,Moderately Contributing,12
27,total_purchases,0.155399,0.031192,Moderately Contributing,13
7,MntMeatProducts,0.170907,0.015684,Moderately Contributing,14
14,NumStorePurchases,0.172655,0.013936,Moderately Contributing,15
18,AcceptedCmp5,0.175064,0.011526,Moderately Contributing,16
5,MntWines,0.176945,0.009646,Low Influence,17
31,family_load,0.177119,0.009472,Low Influence,18
32,is_long_tenure,0.179183,0.007408,Low Influence,19
26,total_spending,0.179320,0.007270,Low Influence,20
13,NumCatalogPurchases,0.181487,0.005104,Low Influence,21
2,Kidhome,0.182441,0.004149,Low Influence,22
29,value_optimizer,0.182624,0.003966,Low Influence,23
8,MntFishProducts,0.183514,0.003076,Low Influence,24
3,Teenhome,0.184987,0.001604,Low Influence,25
28,is_web_dominant,0.185099,0.001491,Low Influence,26
17,AcceptedCmp4,0.186114,0.000476,Low Influence,27
6,MntFruits,0.186250,0.000341,Low Influence,28
9,MntSweetProducts,0.186672,-0.000081,Potential Noise,29
15,NumWebVisitsMonth,0.188263,-0.001673,Potential Noise,30
22,Response,0.188776,-0.002185,Potential Noise,31
24,Education_ord,0.192497,-0.005907,Potential Noise,32
19,AcceptedCmp1,0.192713,-0.006123,Potential Noise,33

Since clustering is an **unsupervised learning task**, there is no target variable to evaluate feature importance directly.  
To assess how each feature contributes to the clustering structure, we performed a **Leave-One-Feature-Out (LOFO) analysis** using K-Means clustering and the **Silhouette Score** as the evaluation metric.

The process was conducted as follows:

1. Compute a **baseline silhouette score** using all available features.
2. Iteratively **remove one feature at a time** from the dataset.
3. Re-run the clustering model on the reduced feature set.
4. Measure the **new silhouette score** obtained without that feature.
5. Compute the **Impact** as:

**Interpretation:**

- **Positive Impact** → Removing the feature **reduces cluster quality**, meaning the feature contributes positively to cluster separation.
- **Near-Zero Impact** → The feature has **little influence** on clustering structure.
- **Negative Impact** → Removing the feature **improves clustering**, suggesting the feature may introduce noise or redundancy.

This approach provides an **unsupervised proxy for feature importance**, helping identify which variables meaningfully shape the geometry of the clustering space.

---

**Key Observations**

**Strongly Influential Features**

Several features show a **large positive impact**, indicating that they are important for distinguishing clusters:

These variables appear to capture **important behavioral and economic dimensions** such as customer lifecycle stage, financial capacity, promotional sensitivity, and engagement with the brand.

---

**Moderately Contributing Features**

Some features contribute to cluster formation but with **smaller influence**:

These features still add information but may partially overlap with other variables.

---

**Low Influence Features**

A number of variables show **very small impact**, meaning removing them barely changes the clustering quality:

These features likely carry information that is already captured by other variables.

---

**Potential Noise Features**

Some features produce **negative impact**, meaning the clustering slightly improves when they are removed:

These variables may introduce **noise, redundancy, or weak signals** relative to the other features.

---

**Conclusion & Bottom Line**

The analysis indicates that **economic capacity, customer tenure, promotional engagement, and purchasing behavior** are the most important dimensions shaping the clustering structure.

Based on the LOFO results, the following features appear to **degrade or minimally contribute to clustering quality** and are candidates for removal:

**Features to Drop**

- `AcceptedCmp1`
- `Education_ord`
- `Response`
- `NumWebVisitsMonth`
- `MntSweetProducts`

These variables either introduce noise or provide limited additional information beyond what is already captured by stronger behavioral and financial features.

Removing them helps **simplify the feature space**, reduce redundancy, and improve the clarity of the clustering geometry.

The remaining features will be retained for the next stage of the workflow, which involves **feature transformation and scaling prior to running the final clustering models**.

In [18]:
features_to_drop = [
    'AcceptedCmp1',
    'Education_ord',
    'Response',
    'NumWebVisitsMonth',
    'MntSweetProducts'
]

df = df.drop(columns=features_to_drop)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year_Birth                2240 non-null   int64
 1   Income                    2240 non-null   float64
 2   Kidhome                   2240 non-null   int64
 3   Teenhome                  2240 non-null   int64
 4   Recency                   2240 non-null   int64
 5   MntWines                  2240 non-null   int64
 6   MntFruits                 2240 non-null   int64
 7   MntMeatProducts           2240 non-null   int64
 8   MntFishProducts           2240 non-null   int64
 9   MntGoldProds              2240 non-null   int64
 10  NumDealsPurchases         2240 non-null   int64
 11  NumWebPurchases           2240 non-null   int64
 12  NumCatalogPurchases       2240 non-null   int64
 13  NumStorePurchases         2240 non-null   int64
 14  AcceptedCmp3              2240 non-null   int64
 15  AcceptedCmp4              2240 non-null   int64
 16  AcceptedCmp5              2240 non-null   int64
 17  AcceptedCmp2              2240 non-null   int64
 18  Complain                  2240 non-null   int64
 19  tenure_years              2240 non-null   float64
 20  Marital_Status_encoded    2240 non-null   int64
 21  total_spending            2240 non-null   int64
 22  total_purchases           2240 non-null   int64
 23  is_web_dominant           2240 non-null   int32
 24  value_optimizer           2240 non-null   int32
 25  spending_to_income_ratio  2240 non-null   float64
 26  family_load               2240 non-null   int32
 27  is_long_tenure            2240 non-null   int32
dtypes: float64(3), int32(4), int64(21)
memory usage: 455.1 KB

In [20]:
df.to_pickle(r"C:\Users\Almog\Desktop\Data Science\Projects\2026\Customer Personality Analysis\Pickle files\FS_MC1.pkl")